mywebsite/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog import views as blog_views
from fangtan import views as fangtan_views
from data import views as data_views
from poem import views as poem_views
from wxtj import views as wxtj_views
admin.autodiscover()

urlpatterns =[
    # Examples:
    # url(r'^$', 'mywebsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^$',blog_views.index,name='index'),
    url(r'^detail/$', blog_views.detail,name='detail'),
    url(r'^fangtan/$',fangtan_views.all_duixiang,name='all_duixiang'),
    url(r'^fangtan/report/(?P<duixiang_id>[0-9]+)/',fangtan_views.report_list,name='report_list'),
    url(r'^fangtan/report_detail/(?P<report_id>[0-9]+)/',fangtan_views.report_detail,name='report_detail'),
    url(r'^fangtan/report/empty/$',fangtan_views.report_empty,name='report_empty'),
    url(r'^data/$',data_views.user,name='user'),
    url(r'^poem/random/$',poem_views.random_poem,name='random_poem'),
    url(r'^poem/test/$',poem_views.test,name='test'),
    url(r'^wxtj/',wxtj_views.wxtj,name='wxtj'),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

data/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

fangtan/models.py
#-*-coding:utf-8-*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class duixiang(models.Model):
    picture=models.ImageField(blank=True)
    name=models.CharField(max_length=20)
    sex=models.CharField(max_length=10,choices=[('m',u'男'),('f',u'女')])
    university=models.CharField(max_length=20)
    grade=models.PositiveSmallIntegerField(choices=[(1,u'大一'),(2,'大二'),(3,'大三'),(4,'大四')])
    homeland=models.CharField(max_length=10)
    major=models.CharField(max_length=10)
    label=models.CharField(max_length=20)
    income=models.CharField(max_length=10,choices=[('poor',u'贫穷'),('normal',u'一般'),('rich',u'富裕'),('super',u'土豪')])
    elseinfo=models.TextField(blank=True)

    def __unicode__(self):
        return self.name+''+self.university

class report(models.Model):
    time=models.DateField()
    origin=models.FileField()
    ctic=models.TextField(blank=True)
    report_to=models.ForeignKey(duixiang,on_delete=models.CASCADE)

    def __unicode__(self):
        return unicode(self.time)+self.report_to.name

poem/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

wxtj/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class wxwz(models.Model):
    post_date = models.DateField()
    pos = models.PositiveSmallIntegerField()
    title = models.CharField(max_length = 100)
    title_type = models.CharField(max_length=10,choices=[('zy','直言'),('as','暗示'),('xz','新知'),('tw','提问'),('ml','命令'),('pd','盘点'),('rx','人性'),('dr','代入'),('jq','节气'),('rd','热点'),('zht','知乎体'),('dbkz','对比夸张')])
    con_type = models.CharField(max_length=10)
    share = models.IntegerField(blank = True)
    view = models.IntegerField(blank = True)
    like = models.IntegerField(blank = True)
    forward = models.IntegerField(blank = True)
    score = models.IntegerField(blank = True)
    url = models.CharField(blank = True, max_length = 200)
    author = models.CharField(blank = True, max_length = 10)
    center = models.CharField(blank = True, max_length = 10)

    def __unicode__(self):
        return self.title

blog/views.py
#-*-coding:utf-8-*-
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return HttpResponse(u'这是首页，应该展示最近的博客列表')

def detail(request):
    return HttpResponse(u'这是详情页，展示一篇博客的全部内容')

data/views.py
#coding:utf-8
from django.shortcuts import render
from django.http import HttpResponse
import string,urllib,urllib2,re,cookielib,datetime,json,hashlib

# Create your views here.
def md5(s):
    m=hashlib.md5()
    m.update(s)
    return m.hexdigest()

def user(request):
    #保存cookie的文件
    filename='cookie.txt'

    #获取cookie
    cookie=cookielib.MozillaCookieJar(filename)
    handler=urllib2.HTTPCookieProcessor(cookie)
    opener=urllib2.build_opener(handler)


    values = {'username':'3278663871@qq.com',
              'pwd':md5('5252mayi')}#向登录页面post的数据
    data=urllib.urlencode(values)#数据url编码
    headers={'Referer':'https://mp.weixin.qq.com/',
             'User-Agent':'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36',
             'Connection': 'keep-alive',
             'Accept':'*/*',
             }#request header信息
    request=urllib2.Request('https://mp.weixin.qq.com/cgi-bin/login',data,headers)
    response=opener.open(request)#response内容，为一file对象实例
    cookie.save(ignore_discard=True, ignore_expires=True)#cookie保存
    #获取请求具体页面的token
    now=datetime.datetime.now()
    time=now.strftime('%Y%m%d %H%M%S')
    end_time=now.strftime('%Y-%m-%d')
    p1=re.compile(r'token=(.+)"')
    token_list=p1.findall(response.read())
    token=token_list[0]
    begin_date=raw_input('enter begin date:')
    data={'download':'1',
          'begin_date':'2016-02-01',
          'end_date':end_time,
          'source':'99999999',
          'token':token,
          'lang':'zh_CN',}
    url1='https://mp.weixin.qq.com/misc/useranalysis?&'+urllib.urlencode(data)
    con_req=urllib2.Request(url1)
    con_resp=opener.open(con_req).read()
    return HttpResponse(con_resp)

fangtan/views.py
import sys
reload(sys)
sys.setdefaultencoding( "utf-8" )

from django.shortcuts import render
from fangtan.models import duixiang,report
import string,re,jieba,jieba.analyse,pyglet,pytagcloud
from django.http import HttpResponse
from operator import itemgetter
# Create your views here.

def segf(content):
    out=jieba.cut(content,cut_all=False)
    nonsense=[]
    word_freq={}
    for x in out:
        if len(x)<2:
            continue
        elif x in nonsense:
            continue
        else:
            c=str(x)
            if x not in word_freq:
                word_freq[x]=1
            else:
                word_freq[x]+=1
    word_freq=sorted(word_freq.iteritems(), key=itemgetter(1), reverse=True)
    return word_freq


def all_duixiang(request):
    duixiang_list=duixiang.objects.all()
    context={'duixiang_list':duixiang_list,}

    return render(request,'fangtan/duixiang.html',context)

def report_list(request,duixiang_id):
    dx=duixiang.objects.get(pk=duixiang_id)
    report_list=dx.report_set.all()
    context={'report_list':report_list,}

    return render(request,'fangtan/report.html',context)

def report_detail(request,report_id):
    rep=report.objects.get(pk=report_id)
    content=rep.origin.read().replace('\n','<br>')
    fenxi=segf(content)
    string=' '
    for (k,v) in fenxi:
        string=string+k+' '+str(v)+'<br>'
    context={'content':content,
             'ctic':rep.ctic,
             'fenxi':string,}

    return render(request,'fangtan/report_detail.html',context)

def report_empty(request):
    return HttpResponse(u'<h1>No message</h1>')

poem/views.py
#coding:utf8
from django.shortcuts import render
from django.http import HttpResponse
import re,random

# Create your views here.
def random_poem(request):
    with open('result.txt','r') as f:
        con=f.readlines()#con：所有诗的列表
        ran=random.choice(con)#ran：某首诗
        rlist=re.split(r'【|】|；|,|）|，|。|？|！|：',ran)
        title=rlist[1]
        if '（' in rlist[2]:
            plist=rlist[3:]#plist的元素：一首诗中的某一行
        else:
            plist=rlist[2:]
        plist=[i.strip() for i in plist]
        for i in random.sample(range(len(plist)-1),1):#随机生成空缺句
            answer=plist[i].strip().decode('utf-8')
            plist[i]=' '#此时，plist保存了一首诗的各行和一个空行
        answerlist=[answer[i] for i in range(len(answer))]#answerlist保存正确句中各个单字
        miss=random.sample(''.join(plist).decode('utf-8'),12-len(answer))#补充到12个字
        guesslist=miss+answerlist#guesslist中共12个单字，其中包含answerlist的正确和miss中的补充
        random.shuffle(guesslist)#打乱顺序的guesslist
        context={'plist':plist,'title':title,
                 'answer':answer,'answerlist':answerlist,
                 'guesslist':guesslist,'indexlist':range(12),}
        return render(request,'poem/index.html',context)
        
def test(request):
    return render(request,'poem/test.html')
    
    

wxtj/views.py
import sys
reload(sys)
sys.setdefaultencoding( "utf-8" )

from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def wxtj(request):
    return HttpResponse(u'weixin tongji ')

data/templates/data/show.html
<!doctype html>
<html lang="cn">
<head>
	<meta charset="UTF-8">
	<title>data_show</title>
</head>
<body>
	
</body>
</html>

fangtan/templates/fangtan/duixiang.html
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>访谈对象集</title>
<style type='text/css'>
table {border:1px solid #000;}
body,table{ 
font-size:12px; 
} 
table{ 
table-layout:fixed; 
empty-cells:show; 
border-collapse: collapse; 
margin:0 auto; 
} 
td{ 
height:30px;
} 
h1,h2,h3{ 
font-size:12px; 
margin:0; 
padding:0; 
} 
.table{ 
border:1px solid #cad9ea; 
color:#666; 
} 
.table th { 
background-repeat:repeat-x; 
height:30px; 
} 
.table td,.table th{ 
border:1px solid #cad9ea; 
padding:0 1em 0; 
} 
.table tr.alter{ 
background-color:#f5fafe; 
} 
</style>
</head>
<body>
<table class='table'>
<tr>
	<th>姓名</th>
	<th>性别</th>
	<th>学校</th>
	<th>专业</th>
	<th>年级</th>
	<th>家乡</th>
	<th>标签</th>
	<th>收入水平</th>
	<th>其他信息</th>
	<th>具体报告</th>
</tr>
{% for duixiang in duixiang_list %}
	<tr>
	<td>{{duixiang.name}}</td>
	<td>{{duixiang.get_sex_display}}</td>
	<td>{{duixiang.university}}</td>
	<td>{{duixiang.major}}</td>
	<td>{{duixiang.get_grade_display}}</td>
	<td>{{duixiang.homeland}}</td>
	<td>{{duixiang.label}}</td>
	<td>{{duixiang.get_income_display}}</td>
	<td>{{duixiang.elseinfo}}</td>
	<td><a href="{% url 'report_list' duixiang.id%}" target="_blank">点击查看</td>
	</tr>
{% endfor %}
</table>
</body>
</html>

fangtan/templates/fangtan/report.html
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>访谈记录</title>
<style type="text/css"> 
table {border:1px solid #000;}
body,table{ 
font-size:12px; 
} 
table{ 
table-layout:fixed; 
empty-cells:show; 
border-collapse: collapse; 
margin:0 auto; 
} 
td{ 
height:30px; 
} 
h1,h2,h3{ 
font-size:12px; 
margin:0; 
padding:0; 
} 
.table{ 
border:1px solid #cad9ea; 
color:#666; 
} 
.table th { 
background-repeat:repeat-x; 
height:30px; 
} 
.table td,.table th{ 
border:1px solid #cad9ea; 
padding:0 1em 0; 
} 
.table tr.alter{ 
background-color:#f5fafe; 
} 
iframe{margin:40px;}
</style>
</head>
<body>
<table class='table'>
<tr>
	<th>记录时间</th>
	<th>原始记录下载</th>
	<th>详细内容</th>
</tr>
{% for report in report_list %}
	<tr>
	<td>{{report.time}}</td>
	<td><a href="{{report.origin.url}}">右键链接另存为</a></td>
	<td><a href="{% url 'report_detail' report.id%}" target="show_frame">查看</a></td>
	</tr>
{% endfor %}
</table>
<iframe src="{% url 'report_empty' %}" name="show_frame" width='90%' height='800px'></iframe>
</body>
</html>

fangtan/templates/fangtan/report_detail.html
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>详情</title>
<style type="text/css"> 
table {border:1px solid #000;}
body,table{ 
font-size:12px; 
} 
table{ 
table-layout:fixed;
empty-cells:show; 
border-collapse: collapse; 
margin:0 auto; 
} 
td{ 
height:100px;
width:33%; 
text-align:left;
vertical-align:top; 

} 
h1,h2,h3{ 
font-size:12px; 
margin:0; 
padding:0; 
} 
.table{ 
border:1px solid #cad9ea; 
color:#666; 
} 
.table th { 
background-repeat:repeat-x; 
height:30px; 
} 
.table td,.table th{ 
border:1px solid #cad9ea; 
padding:0 1em 0; 
} 
.table tr.alter{ 
background-color:#f5fafe; 
} 
iframe{margin:40px;}
</style>
</head>
<body>

<table class='table'>
	<tr>
		<th>原始内容</th>
		<th>评论内容</th>
		<th>语义分析关键词</th>
	</tr>
	{% autoescape off %}
	<tr>
		<td>{{content}}</td>
		<td>{{ctic}}</td>
		<td>{{fenxi}}</td>
	</tr>
	{% endautoescape %}
</table>

</body>
</html>

poem/templates/poem/index.html
<!doctype html>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>你还记得吗？</title>
<!--<script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.1.1/jquery.min.js"></script>-->

<script type='text/javascript'>
$(document).ready(function(){
{%for i in indexlist%}
$('#single{{i}}').click(function(){
$('#fillin').val($('#fillin').val()+$('#single{{i}}').text());
});
{%endfor%}
});
</script>
</head>

<body>
<h2>{{title}}</h2>
{%for p in plist%}
{%if p == ' '%}
<input type="text" id='fillin' />
{%else%}
<div>{{p}}</div>
{%endif%}
{%endfor%}
<br />
<div class='answer' style='display:none'>{{answer}}</div>

{%for a in guesslist%}
<button class='guess' id='single{{forloop.counter0}}'>{{a}}</button>
{%endfor%}
</body>

</html>

poem/templates/poem/test.html
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>你还记得吗？</title>
<script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.1.1/jquery.min.js"></script>

<script type='text/javascript'>
$(document).ready(function(){
$("#answer").click(function(){
$(".answer").show();
});
var i=0;
function newquestion(){
$.get('{%url 'random_poem'%}',function(result){
$('.container').html(result);
});
};
$('#sumbit').click(function(){
if($('#fillin').val()==$('.answer').text()){
i=i+1;
alert('正确');
$('#result').text(i);
newquestion();
}
else{
alert('错误，重新开始');
i=0;
$('#result').text('0');
newquestion();
};
});

$('#skip').click(function(){
newquestion();
});
newquestion();
});
</script>

</head>
<body>
<div class="container"></div>
<!--<button class='button' id='answer'>查看答案</button>-->
<button class='button' id='sumbit'>提交</button>
<button class='button' id='skip'>跳过</button>
<div>正确数：<b><span id='result'>0</span></b></div>
<br />
<br />
</body>
</html>